name: 'Unit Tests'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Composer 8
        uses: php-actions/composer@v5
        with:
          php_version: 8
      - name: PHP 8 tests
        run: ./vendor/bin/pest
        with:
          php_version: 8